version: '3.8'

services:

  nginx_to_jenkins:
    image: nginx:latest
    container_name: nginx_to_jenkins
    hostname: nginx_to_jenkins
    restart: unless-stopped
    depends_on:
      - jenkins_master
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jenkins_network
    ports:
      - 80:80

  jenkins_master:
    image: jenkins/jenkins:2.361.2-lts-jdk11
    container_name: jenkins_master
    hostname: jenkins_master
    restart: unless-stopped
    volumes:
      - jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    ports:
      - 8080:8080
      - 50000:50000

  jenkins_agent:
    image: jenkins/inbound-agent
    container_name: jenkins_agent
    hostname: jenkins_agent
    # user 'root' needed for installing packages in Jenkins pipeline running on this node
    # if we use default user (jenkins), we need to execute command on this node
    #   docker exec -it -u root jenkins_agent /bin/bash -c "apt update -y && apt install -y ..."
    user: root
    restart: unless-stopped
    depends_on:
      - jenkins_master
    volumes:
      - jenkins_agent_jenkins:/home/jenkins/.jenkins
      - jenkins_agent_agent:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    environment:
      JENKINS_URL: http://jenkins_master:8080
      JENKINS_SECRET: 35a6f77f603dbef0811aaca31cd46211ef46dcb9ff7bf34ce66d71e712ace89d
      JENKINS_AGENT_NAME: agent_1
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent

volumes:
  jenkins_volume:
    name: jenkins_volume
  jenkins_agent_jenkins:
    name: jenkins_agent_jenkins
  jenkins_agent_agent:
    name: jenkins_agent_agent

networks:
  jenkins_network:
    name: jenkins_network
