---
- name: Docker-users | Ensure docker users are added to the docker group.
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"

- name: Docker-users | Reset ssh connection to apply user changes.
  ansible.builtin.meta: reset_connection
