def github_cred_id = 'Github-senkodima'
def github_url = 'git@github.com:senkodima/DevOps-Project.git'

def dockerhub_cred_id = 'dockerhub-senkodima'
def dockerhub_repo_name = 'senkodima'

def app_name = 'flask-app'

def git_commit
def imageName
def docker_image

def get_build_status(status) {
  if (status == 'RUN') {
    return "[🕐] Start running 😴"
  }
  if (status == 'SUCCESS') {
    return "[✅] Build successfully 😊"
  } 
  if (status == 'FAILURE') {
    return "[❌] Failed to build 😱\n" + 
           "Failing in '${env.FAILURE_STAGE}' stage"
  }
  if (status == 'ABORTED') {
    return "[❎] Build aborted 😵"
  }
}

def telegram_notification(TOKEN, CHAT_ID, build_status) {
    script {
        sh (label: 'Telegram notification', script: """ 
curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage \
-d chat_id=${CHAT_ID} -d parse_mode=HTML -d text="\
<b>JOB:</b> ${env.JOB_NAME}\n\
<b>STATUS:</b> ${build_status}\n\
<b>BRANCH:</b> $Branch\n\
<b>BUILD_ID:</b> <a href=\\"${env.BUILD_URL}\\">${env.BUILD_ID}</a>\n\
<b>DURATION:</b> ${currentBuild.durationString}"
        """)
    }
}

def Branch = 'main'

pipeline {
    triggers { 
        cron('* * * * *')
    }
    stages {
        agent { 
            label 'agent_ubuntu_prod' // or use label 'agent_1'
        }
        stage('Checkout SCM') {
            steps {
                script {
                    echo "This stage - '$STAGE_NAME'"
                    git branch: "$Branch", credentialsId: "$gitlab_credId", url: "$gitlabUrl"
                    git_commit = sh(label: 'Short Git Commit', returnStdout: true, 
                                    script: 'git rev-parse --short=7 HEAD').trim()
                }
            }
            post { failure { script { env.FAILURE_STAGE = "$STAGE_NAME" } } }
        }
    }
    post {
        always {
            script {
                echo 'Post always ...'
                withCredentials([string(credentialsId: 'telegram_bot_token', variable: 'TOKEN'), 
                                 string(credentialsId: 'telegram_chat_id', variable: 'CHAT_ID')]) {
                    def build_status = get_build_status(currentBuild.currentResult)
                    telegram_notification(TOKEN, CHAT_ID, build_status)
                }
                // remove local images if it still exists
                // sh "docker rmi --force \$(docker images -q ${docker_image.id} | uniq) || true"
            }
        }
        success {
            echo 'Post success ...'
            // cleanWs() // Clean after build
        }
        aborted {
            echo 'Post aborted ...'
            // cleanWs() // Clean
        }
        failure {
            echo 'Post failure ...'
            // cleanWs() // Clean
        }
    }
}
